/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idiomas.vistas;

import idiomas.modelos.Idioma;
import idiomas.modelos.ModeloTablaIdiomas;
import interfaces.IControladorIdiomas;
import javax.swing.JTable;
import principal.vistas.VentanaPrincipal;

public class VentanaIdiomas extends javax.swing.JDialog {
    private IControladorIdiomas controlador;
    /**
     * Creates new form VentanaAIdiomas
     */
    public VentanaIdiomas(VentanaPrincipal padre, boolean modal, IControladorIdiomas controlador) {
        super(padre, modal);
        initComponents();
        this.tablaIdiomas.setModel(new ModeloTablaIdiomas());
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarIdioma = new javax.swing.JTextField();
        btnBuscarIdioma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIdiomas = new javax.swing.JTable();
        btnNuevoIdioma = new javax.swing.JButton();
        btnBorrarIdioma = new javax.swing.JButton();
        btnVolverIdioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Idiomas");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                VentanaObtenerFoco(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Nombre:");

        txtBuscarIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdiomasPresionarTecla(evt);
            }
        });

        btnBuscarIdioma.setText("Buscar");
        btnBuscarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdiomaClic(evt);
            }
        });

        tablaIdiomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaIdiomas);

        btnNuevoIdioma.setText("Nuevo");
        btnNuevoIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoIdiomaClic(evt);
            }
        });

        btnBorrarIdioma.setText("Borrar");
        btnBorrarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarIdiomaClic(evt);
            }
        });

        btnVolverIdioma.setText("Volver");
        btnVolverIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIdiomaClic(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevoIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnBorrarIdioma)
                        .addGap(36, 36, 36)
                        .addComponent(btnVolverIdioma))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoIdiomaClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoIdiomaClic
        this.controlador.btnNuevaClic(evt);
    }//GEN-LAST:event_btnNuevoIdiomaClic

    private void btnVolverIdiomaClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIdiomaClic
        this.controlador.btnVolverClic(evt);
    }//GEN-LAST:event_btnVolverIdiomaClic

    private void txtIdiomasPresionarTecla(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdiomasPresionarTecla
        this.controlador.txtIdiomaPresionarTecla(evt);
    }//GEN-LAST:event_txtIdiomasPresionarTecla

    private void btnBuscarIdiomaClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdiomaClic
        this.controlador.btnBuscarClic(evt);
    }//GEN-LAST:event_btnBuscarIdiomaClic

    private void btnBorrarIdiomaClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarIdiomaClic
        if(this.tablaIdiomas.getSelectedRow() >= 0){
            this.controlador.btnBorrarClic(evt);   
        }
    }//GEN-LAST:event_btnBorrarIdiomaClic

    private void VentanaObtenerFoco(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_VentanaObtenerFoco
        this.controlador.ventanaObtenerFoco(evt);
    }//GEN-LAST:event_VentanaObtenerFoco

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
     
    }
    
    public JTable getTablaIdiomas() {
        return tablaIdiomas;
    }
    
    public void idiomasCargados(){
        if (this.tablaIdiomas.getRowCount() == 0){
            this.btnBorrarIdioma.setEnabled(false);
        }
        else {
            this.btnBorrarIdioma.setEnabled(true);
            
        }
        
    }
    
    public Idioma getIdioma(){
        ModeloTablaIdiomas mti = (ModeloTablaIdiomas)this.tablaIdiomas.getModel();
        return mti.verIdioma(this.tablaIdiomas.getSelectedRow());
    }
    
    public String getBusquedaIdiomas() {
        return this.txtBuscarIdioma.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarIdioma;
    private javax.swing.JButton btnBuscarIdioma;
    private javax.swing.JButton btnNuevoIdioma;
    private javax.swing.JButton btnVolverIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaIdiomas;
    private javax.swing.JTextField txtBuscarIdioma;
    // End of variables declaration//GEN-END:variables
}
